// <auto-generated />
using System;
using AuditReadiness.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AuditReadiness.Infrastructure.Migrations
{
    [DbContext(typeof(AuditReadinessDbContext))]
    [Migration("20260715085208_InitialTransactionalSchema")]
    partial class InitialTransactionalSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "uuid-ossp");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AuditReadiness.Domain.AuditActivityLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ActionType")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("action_type");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("EntityId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("entity_id");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("entity_type");

                    b.Property<string>("NewValue")
                        .HasColumnType("jsonb")
                        .HasColumnName("new_value");

                    b.Property<string>("OldValue")
                        .HasColumnType("jsonb")
                        .HasColumnName("old_value");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uuid")
                        .HasColumnName("workspace_id");

                    b.HasKey("Id");

                    b.HasIndex("WorkspaceId", "CreatedAt");

                    b.ToTable("audit_activity_logs", (string)null);
                });

            modelBuilder.Entity("AuditReadiness.Domain.AuditEvidence", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("EvidenceCategory")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("evidence_category");

                    b.Property<string>("EvidenceDescription")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("evidence_description");

                    b.Property<string>("FileName")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("file_name");

                    b.Property<long?>("FileSize")
                        .HasColumnType("bigint")
                        .HasColumnName("file_size");

                    b.Property<string>("IsoStandard")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("iso_standard");

                    b.Property<string>("MimeType")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("mime_type");

                    b.Property<string>("QuestionKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("question_key");

                    b.Property<string>("SourceProvider")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("source_provider");

                    b.Property<string>("SourceUrl")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("source_url");

                    b.Property<string>("StorageUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("storage_url");

                    b.Property<string>("ThemeCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("theme_code");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UploadedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("uploaded_by");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("version");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uuid")
                        .HasColumnName("workspace_id");

                    b.HasKey("Id");

                    b.HasIndex("UploadedBy");

                    b.HasIndex("WorkspaceId", "QuestionKey");

                    b.ToTable("audit_evidence", (string)null);
                });

            modelBuilder.Entity("AuditReadiness.Domain.AuditMasterQuestion", b =>
                {
                    b.Property<string>("QuestionKey")
                        .HasColumnType("text")
                        .HasColumnName("question_key");

                    b.Property<string>("ApplicableFunction")
                        .HasColumnType("text")
                        .HasColumnName("applicable_function");

                    b.Property<string>("AuditQuestion")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("audit_question");

                    b.Property<string>("AuditorGuideline")
                        .HasColumnType("text")
                        .HasColumnName("auditor_guideline");

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Evidence")
                        .HasColumnType("text")
                        .HasColumnName("evidence");

                    b.Property<string>("Iso14001")
                        .HasColumnType("text")
                        .HasColumnName("iso_14001");

                    b.Property<string>("Iso22301")
                        .HasColumnType("text")
                        .HasColumnName("iso_22301");

                    b.Property<string>("Iso37001")
                        .HasColumnType("text")
                        .HasColumnName("iso_37001");

                    b.Property<string>("Iso45001")
                        .HasColumnType("text")
                        .HasColumnName("iso_45001");

                    b.Property<string>("Iso9001")
                        .HasColumnType("text")
                        .HasColumnName("iso_9001");

                    b.Property<string>("KpiReview")
                        .HasColumnType("text")
                        .HasColumnName("kpi_review");

                    b.Property<string>("Objective")
                        .HasColumnType("text")
                        .HasColumnName("objective");

                    b.Property<string>("RiskReview")
                        .HasColumnType("text")
                        .HasColumnName("risk_review");

                    b.Property<string>("SystemDomain")
                        .HasColumnType("text")
                        .HasColumnName("system_domain");

                    b.Property<string>("ThemeCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("theme_code");

                    b.Property<string>("WhatToVerify")
                        .HasColumnType("text")
                        .HasColumnName("what_to_verify");

                    b.HasKey("QuestionKey");

                    b.ToTable("audit_master_questions", null, t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("AuditReadiness.Domain.AuditMasterTheme", b =>
                {
                    b.Property<string>("ThemeId")
                        .HasColumnType("text")
                        .HasColumnName("theme_id");

                    b.Property<string>("ApplicableFunction")
                        .HasColumnType("text")
                        .HasColumnName("applicable_function");

                    b.Property<string>("AuditObjective")
                        .HasColumnType("text")
                        .HasColumnName("audit_objective");

                    b.Property<string>("AuditTheme")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("audit_theme");

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("PrimaryFocus")
                        .HasColumnType("text")
                        .HasColumnName("primary_focus");

                    b.Property<string>("RelatedIsoStandards")
                        .HasColumnType("text")
                        .HasColumnName("related_iso_standards");

                    b.HasKey("ThemeId");

                    b.ToTable("audit_master_themes", null, t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("AuditReadiness.Domain.AuditQuestionAssessment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AssessmentResult")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("assessment_result");

                    b.Property<string>("AssignedPerson")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("assigned_person");

                    b.Property<string>("AuditeeResponse")
                        .HasMaxLength(5000)
                        .HasColumnType("character varying(5000)")
                        .HasColumnName("auditee_response");

                    b.Property<string>("AuditorNotes")
                        .HasMaxLength(5000)
                        .HasColumnType("character varying(5000)")
                        .HasColumnName("auditor_notes");

                    b.Property<bool>("ChecklistCompleted")
                        .HasColumnType("boolean")
                        .HasColumnName("checklist_completed");

                    b.Property<string>("ChecklistStatus")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("checklist_status");

                    b.Property<string>("CorrectiveAction")
                        .HasMaxLength(5000)
                        .HasColumnType("character varying(5000)")
                        .HasColumnName("corrective_action");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<DateOnly?>("DueDate")
                        .HasColumnType("date")
                        .HasColumnName("due_date");

                    b.Property<string>("QuestionKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("question_key");

                    b.Property<DateTimeOffset?>("ReviewedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("reviewed_at");

                    b.Property<Guid?>("ReviewedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("reviewed_by");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uuid")
                        .HasColumnName("workspace_id");

                    b.HasKey("Id");

                    b.HasIndex("WorkspaceId", "AssessmentResult");

                    b.HasIndex("WorkspaceId", "QuestionKey")
                        .IsUnique();

                    b.ToTable("audit_question_assessments", (string)null);
                });

            modelBuilder.Entity("AuditReadiness.Domain.AuditWorkspace", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AuditFunction")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("audit_function");

                    b.Property<DateOnly>("AuditPeriodEnd")
                        .HasColumnType("date")
                        .HasColumnName("audit_period_end");

                    b.Property<DateOnly>("AuditPeriodStart")
                        .HasColumnType("date")
                        .HasColumnName("audit_period_start");

                    b.Property<string>("AuditeeId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("auditee_id");

                    b.Property<string>("AuditeeName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("auditee_name");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<Guid?>("LeadAuditorId")
                        .HasColumnType("uuid")
                        .HasColumnName("lead_auditor_id");

                    b.Property<string>("LeadAuditorName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("lead_auditor_name");

                    b.Property<string[]>("SelectedIsoStandards")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("selected_iso_standards");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .IsConcurrencyToken()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("WorkspaceName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("workspace_name");

                    b.Property<string>("WorkspaceStatus")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("workspace_status");

                    b.HasKey("Id");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("AuditeeId", "WorkspaceStatus");

                    b.ToTable("audit_workspaces", (string)null);
                });

            modelBuilder.Entity("AuditReadiness.Domain.AuditWorkspaceMember", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("MemberRole")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("member_role");

                    b.Property<string>("UserEmail")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("user_email");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("user_name");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uuid")
                        .HasColumnName("workspace_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("WorkspaceId", "UserId")
                        .IsUnique();

                    b.ToTable("audit_workspace_members", (string)null);
                });

            modelBuilder.Entity("AuditReadiness.Domain.AuditActivityLog", b =>
                {
                    b.HasOne("AuditReadiness.Domain.AuditWorkspace", "Workspace")
                        .WithMany()
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Workspace");
                });

            modelBuilder.Entity("AuditReadiness.Domain.AuditEvidence", b =>
                {
                    b.HasOne("AuditReadiness.Domain.AuditWorkspace", "Workspace")
                        .WithMany("Evidence")
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Workspace");
                });

            modelBuilder.Entity("AuditReadiness.Domain.AuditQuestionAssessment", b =>
                {
                    b.HasOne("AuditReadiness.Domain.AuditWorkspace", "Workspace")
                        .WithMany("Assessments")
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Workspace");
                });

            modelBuilder.Entity("AuditReadiness.Domain.AuditWorkspaceMember", b =>
                {
                    b.HasOne("AuditReadiness.Domain.AuditWorkspace", "Workspace")
                        .WithMany("Members")
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Workspace");
                });

            modelBuilder.Entity("AuditReadiness.Domain.AuditWorkspace", b =>
                {
                    b.Navigation("Assessments");

                    b.Navigation("Evidence");

                    b.Navigation("Members");
                });
#pragma warning restore 612, 618
        }
    }
}
